# Generated by Django 3.2.20 on 2023-08-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_email_user_email'),
        ('accounts', '0002_user_image'),
    ]

    operations = [
    ]
