# Generated by Django 4.2.4 on 2023-08-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
