# Generated by Django 3.2.20 on 2023-08-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230825_0331'),
        ('accounts', '0011_alter_code_user'),
    ]

    operations = [
    ]
