# Generated by Django 4.2.4 on 2023-08-23 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0003_chatroom_chatmessage_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='user_group',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_group',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
