# Generated by Django 4.2.4 on 2023-08-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_board_member'),
        ('channels', '0004_remove_chatroom_user_group_chatroom_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
    ]
