# Generated by Django 4.2.4 on 2023-08-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_matchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrecord',
            name='match',
            field=models.BooleanField(default=False),
        ),
    ]
