# Generated by Django 4.2.4 on 2023-08-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0006_matching_delete_matchrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='image/image.png', null=True, upload_to='Files/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Matching',
        ),
    ]
