# Generated by Django 4.2.4 on 2023-08-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0007_alter_userprofile_image_delete_matching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Files/%Y/%m/%d/'),
        ),
    ]
