# Generated by Django 4.2.4 on 2023-08-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0008_alter_userprofile_image'),
        ('mypage', '0008_remove_userprofile_phone_number_and_more'),
    ]

    operations = [
    ]
