# Generated by Django 4.2.4 on 2023-08-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=20)),
                ('d_title', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('create', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('star', models.BooleanField(default=False)),
                ('people', models.PositiveIntegerField()),
            ],
        ),
    ]
