# Generated by Django 3.2.20 on 2023-08-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=20)),
                ('d_title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('star', models.BooleanField(default=False)),
            ],
        ),
    ]
