# Generated by Django 4.2.4 on 2023-08-22 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
