# Generated by Django 4.2.4 on 2023-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='total',
            field=models.PositiveIntegerField(),
        ),
    ]
