# Generated by Django 4.2.4 on 2023-08-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='completion',
            field=models.BooleanField(default=False),
        ),
    ]
