# Generated by Django 4.2.4 on 2023-08-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_board_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
    ]
