# Generated by Django 4.2.4 on 2023-08-24 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0011_board_now_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
