# Generated by Django 4.2.4 on 2023-08-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_walkboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalkBoard',
        ),
    ]
