<<<<<<< HEAD
# Generated by Django 3.2.20 on 2023-08-24 18:31
=======
# Generated by Django 4.2.4 on 2023-08-24 16:44
>>>>>>> e2482699a960ca5935731b19e8719a2120ca98f4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_walkboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalkBoard',
        ),
    ]
