# Generated by Django 3.2.20 on 2023-08-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_walkboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalkBoard',
        ),
    ]
