# Generated by Django 4.2.4 on 2023-08-24 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0013_walkboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
