# Generated by Django 3.2.20 on 2023-08-24 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_alter_walkboard_user'),
        ('board', '0014_delete_walkboard'),
    ]

    operations = [
    ]
